"""create base

Revision ID: aef70b7d3144
Revises: 
Create Date: 2024-12-04 18:45:23.731522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef70b7d3144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_calculation', sa.DateTime(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('initial_cost', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('calculated_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_results_id'), 'calculation_results', ['id'], unique=False)
    op.create_table('tariff_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_tariff_dates_id'), 'tariff_dates', ['id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['tariff_dates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_tariff_dates_id'), table_name='tariff_dates')
    op.drop_table('tariff_dates')
    op.drop_index(op.f('ix_calculation_results_id'), table_name='calculation_results')
    op.drop_table('calculation_results')
    # ### end Alembic commands ###
